# config.yml
# Multiline is supported!
# {player_name} - Display the players name

Join: '&8[&a+&8] &7{player_name}'
Quit: '&8[&c-&8] &7{player_name}'

#Messages
#Randon true / false - if false defaults to message 0
random-mode: true

Messages:
  '0':
    Message:
      - '&8&m-----------------------------------------------------'
      - 'Welcome 1'
      - '&eEnjoy your stay!'
      - '&8&m-----------------------------------------------------'
      - ''
  '1':
    Message:
      - '&8&m-----------------------------------------------------'
      - 'Welcome 1'
      - '&eEnjoy your stay!'
      - '&8&m-----------------------------------------------------'
      - ''
  '2':
    Message:
      - '&8&m-----------------------------------------------------'
      - 'Welcome 1'
      - '&eEnjoy your stay!'
      - '&8&m-----------------------------------------------------'
      - ''
  '3':
    Message:
      - '&8&m-----------------------------------------------------'
      - 'Welcome 1'
      - '&eEnjoy your stay!'
      - '&8&m-----------------------------------------------------'
      - ''